baseURL = "/"
languageCode = "fr-fr"
title = "Le RÃ©glage Parfait"
theme = "PaperMod"

# Forcer Hugo Ã»utiliser des URLs en minuscules
preserveTaxonomyNames = false

[Paginacion] 
    pagerSize = 10

[build]
    target = "production"
    extended = true

[menu]
  [[menu.main]]
    identifier = "accueil"
    name = "Accueil"
    url = "/"
    weight = 10
  [[menu.main]]
    identifier = "materiel"
    name = "MatÃ©riel"
    url = "/tags/materiel/"
    weight = 20
  [[menu.main]]
    identifier = "technique"
    name = "Technique"
    url = "/tags/composition/" 
    weight = 30
  [[menu.main]]
    identifier = "articles"
    name = "Tous les Articles"
    url = "/posts/"
    weight = 40

[params]
    env = "production"
    defaultTheme = "auto"
    showReadingTime = true
    showPostNavButtons = true
    showPageNums = true
    showToc = true

    [params.profileMode]
        enabled = true
        title = "Le RÃ©glage Parfait ðŸ“¸"
        subtitle = "Dominez votre matÃ©riel, sublimez vos images. Guides experts pour photographes exigeants."
        imageUrl = "logo.webp"
        imageWidth = 120
        imageHeight = 120
        [[params.profileMode.buttons]]
            name = "ðŸ“¸ Nos Guides MatÃ©riel"
            url = "/tags/materiel/"
        [[params.profileMode.buttons]]
            name = "ðŸŽ¨ MaÃ®triser la Composition"
            url = "/posts/guide-composition/"

[markup.goldmark.renderer]
    unsafe = true