baseURL = "/"
languageCode = "fr-fr"
title = "Le Réglage Parfait"
theme = "ananke"

# Options Globales de Hugo
enableRobotsTXT = true
disableKinds = ["taxonomy", "term"]
copyright = "© 2025 Le Réglage Parfait. Tous droits réservés."

# Configuration du Menu de Navigation Principal
[menu]
  [[menu.main]]
    identifier = "home"
    name = "Accueil"
    url = "/"
    weight = 10

  [[menu.main]]
    identifier = "articles"
    name = "Guides (Articles)"
    url = "/posts/"
    weight = 20

  [[menu.main]]
    identifier = "about"
    name = "À Propos"
    url = "/about/"
    weight = 30

# ... (vos autres paramètres)

# Paramètres du thème (Ananke)
[params]
  # Chemin absolu du fichier statique
  hero_image = "/images/hero-home.webp"
  # Variable spécifique à Ananke pour la page d'accueil
  ananke_home_image = "/images/hero-home.webp"