baseURL = "/"
languageCode = "fr-fr"
title = "Le RÃ©glage Parfait - Guides Optiques et Photo Pro"
theme = "Ananke"
disableKinds = ["taxonomy", "term"]
enableRobotsTXT = true

[params]
  showHeader = true

[pagination]
  pagerSize = 10

[taxonomies]
  category = 'categories'
  tag = 'tags'
# Ceci est un commentaire pour forcer la reconstruction du build Cloudflare